#!/usr/bin/python
# -*- coding: UTF-8 _*_

# 运营配置位
test_path_list:
  url_ui1: '/test_case/test_Api_demo/test_api_per.py'
  url_ui: '/test_flow/'
  url_ui2: '/test_flow/test_Authentication/test_backStage_authentication.py'
  url_ui_forward: 'https://cjt-uat.chengtay.com/user/login'
  url_ui_back: 'https://cjt-admin-uat.chengtay.com/#/account/login'
  url_ui_register: 'https://cjt-uat.chengtay.com/user/register'
  url_ui_forget: 'https://cjt-uat.chengtay.com/user/forget'
  delete_flag: 0
test_backStageUserList:
  company_user: '13816391517'
  company_user_pass: '123456'
  company_bank_pass: '123456'
  company_Guarantee_pass: '123456'
  company_name: '山东沁园春市政园林工程有限公司'
  autoTest_BankName: 'AutoTest_Bank1008'
  company_bank: '17082200002'
  autoTest_RiskName: 'AutoTest_Risk1008'
  company_Guarantee: '17082300002'
  product_name: '1008号金融产品'
  rend_rule: 2
  rend_day: 2
test_userlist:
  company_user: '17621198933'
  company_user_pass: '123456'
test_db_list:
  host: '10.10.128.128'
  user: 'root'
  password: 'chengtay-uat'
  port: 3306
  db1: 'chengtay-zero'
  db2: 'chengtay-zcd'
  db3: 'chengtay-zcd'
test_redisdb_list:
  host: '10.10.128.128'
  password: 'ctredis6739'
  port: 6739
  db3: '3'
  RequestURL: 'https://zero-api-uat.chengtay.com/v1/account/login'
test_db_sqllist:
    # UI端sql
#    sql0000001: "SET SQL_SAFE_UPDATES = 0;"
#    sql0000002: "DELETE FROM `chengtay-zero`.zero_user where userName = {0};"
#    sql0000003: "DELETE FROM `chengtay-zero`.zero_user_authentication where phoneNo = {0};"
    sql0000004: "SET SQL_SAFE_UPDATES = 0;"
    sql0000005: "update `chengtay-zcd`.enterprise set name = 'oldcompanyname' where name in ('山东沁园春市政园林工程有限公司');"
    sql0000006: "Delete From `chengtay-zero`.zero_user where phoneNo in {0};"
    sql0000007: "Delete From `chengtay-zcd`.product_material where productid in (select id FROM `chengtay-zcd`.product where provide = {0});"
    sql0000008: "Delete FROM `chengtay-zcd`.product where provide = {0};"
    sql0000009: "Delete FROM `chengtay-zcd`.mechanism where id in (select mechanismId FROM `chengtay-zcd`.enterprise_account  where phone in {0});"
    sql0000010: "Delete  FROM `chengtay-zcd`.enterprise where mechanismId in (select mechanismId FROM `chengtay-zcd`.enterprise_account where phone in {0});"
    sql0000011: "Delete  FROM `chengtay-zcd`.enterprise_account where phone in  {0};"
    sql0000012: "DELETE FROM `chengtay-zcd`.enterprise where name IN {0};"
    sql0000013: "DELETE FROM `chengtay-zcd`.mechanism where name IN {0};"
    # 移动端sql
    sql0000014: "delete from `chengtay-zero`.zero_user_auth where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000015: "delete FROM `chengtay-zero`.zero_user where phoneNo ={0};"
    sql0000016: "delete FROM `chengtay-zero`.zero_user_authentication where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000017: "delete from `chengtay-zero`.zero_user_claim  where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000018: "delete from `chengtay-zero`.zero_user_external_login where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000019: "delete from `chengtay-zero`.zero_user_role  where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000020: "delete from `chengtay-zero`.zero_user_auth  where userId in (select id from `chengtay-zero`.zero_user where phoneNo ={0});"
    sql0000021: "delete from `chengtay-zcd`.enterprise_account where phone = {0};"
    sql0000022: "update `chengtay-zcd`.enterprise set name = {0} where name in ('四川海辰日用化工有限公司');"
    sql0000023: "SELECT params FROM `chengtay-zero`.msg_message_sms WHERE phoneNos = {0} AND confKey = 'live.certification' ORDER BY sendTime DESC LIMIT 1;"

test_personalInfoRegList:
  name: '李涛'
  id_card: '`410184198105155611`'


  #银行账户  15111111111  d28wy6
  #担保账户  15222222222  naihdy
  #企业账户  15333333333 123456